kind: Deployment
apiVersion: apps/v1
metadata:
  name: spark-master
spec:
  replicas: 1
  selector:
    matchLabels:
      component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      containers:
        - name: spark-master
          image: spark3:v8
          command: ["/bin/sh","-c"]
          args: ["/opt/spark/docker-configs/spark-thrift;/opt/spark/docker-configs/spark-master;"]
          ports:
            - containerPort: 7077
            - containerPort: 8080
          imagePullPolicy: Never
          resources:
            requests:
              cpu: 1
              memory: 1200Mi
